// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IM.Message.proto

/*
Package IM_Message is a generated protocol buffer package.

It is generated from these files:
	IM.Message.proto

It has these top-level messages:
	IMMsgData
	IMMsgDataAck
	IMMsgDataReadAck
	IMMsgDataReadNotify
	IMClientTimeReq
	IMClientTimeRsp
	IMUnreadMsgCntReq
	IMUnreadMsgCntRsp
	IMGetMsgListReq
	IMGetMsgListRsp
	IMGetLatestMsgIdReq
	IMGetLatestMsgIdRsp
	IMGetMsgByIdReq
	IMGetMsgByIdRsp
*/
package IM_Message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import IM_BaseDefine "github.com/xiaominfc/xiny/pb/IM_BaseDefine"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// service id  0x0003
type IMMsgData struct {
	// cmd id:		0x0301
	FromUserId       *uint32                `protobuf:"varint,1,req,name=from_user_id,json=fromUserId" json:"from_user_id,omitempty"`
	ToSessionId      *uint32                `protobuf:"varint,2,req,name=to_session_id,json=toSessionId" json:"to_session_id,omitempty"`
	MsgId            *uint32                `protobuf:"varint,3,req,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	CreateTime       *uint32                `protobuf:"varint,4,req,name=create_time,json=createTime" json:"create_time,omitempty"`
	MsgType          *IM_BaseDefine.MsgType `protobuf:"varint,5,req,name=msg_type,json=msgType,enum=IM.BaseDefine.MsgType" json:"msg_type,omitempty"`
	MsgData          []byte                 `protobuf:"bytes,6,req,name=msg_data,json=msgData" json:"msg_data,omitempty"`
	AttachData       []byte                 `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *IMMsgData) Reset()                    { *m = IMMsgData{} }
func (m *IMMsgData) String() string            { return proto.CompactTextString(m) }
func (*IMMsgData) ProtoMessage()               {}
func (*IMMsgData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IMMsgData) GetFromUserId() uint32 {
	if m != nil && m.FromUserId != nil {
		return *m.FromUserId
	}
	return 0
}

func (m *IMMsgData) GetToSessionId() uint32 {
	if m != nil && m.ToSessionId != nil {
		return *m.ToSessionId
	}
	return 0
}

func (m *IMMsgData) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgData) GetCreateTime() uint32 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *IMMsgData) GetMsgType() IM_BaseDefine.MsgType {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return IM_BaseDefine.MsgType_MSG_TYPE_SINGLE_TEXT
}

func (m *IMMsgData) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *IMMsgData) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMMsgDataAck struct {
	// cmd id:		0x0302
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,2,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	MsgId            *uint32                    `protobuf:"varint,3,req,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,4,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMMsgDataAck) Reset()                    { *m = IMMsgDataAck{} }
func (m *IMMsgDataAck) String() string            { return proto.CompactTextString(m) }
func (*IMMsgDataAck) ProtoMessage()               {}
func (*IMMsgDataAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMMsgDataAck) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMMsgDataAck) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMMsgDataAck) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgDataAck) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

type IMMsgDataReadAck struct {
	// cmd id:		0x0303
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,2,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	MsgId            *uint32                    `protobuf:"varint,3,req,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,4,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMMsgDataReadAck) Reset()                    { *m = IMMsgDataReadAck{} }
func (m *IMMsgDataReadAck) String() string            { return proto.CompactTextString(m) }
func (*IMMsgDataReadAck) ProtoMessage()               {}
func (*IMMsgDataReadAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IMMsgDataReadAck) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

type IMMsgDataReadNotify struct {
	// cmd id:		0x0304
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,2,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	MsgId            *uint32                    `protobuf:"varint,3,req,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,4,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMMsgDataReadNotify) Reset()                    { *m = IMMsgDataReadNotify{} }
func (m *IMMsgDataReadNotify) String() string            { return proto.CompactTextString(m) }
func (*IMMsgDataReadNotify) ProtoMessage()               {}
func (*IMMsgDataReadNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IMMsgDataReadNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

type IMClientTimeReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IMClientTimeReq) Reset()                    { *m = IMClientTimeReq{} }
func (m *IMClientTimeReq) String() string            { return proto.CompactTextString(m) }
func (*IMClientTimeReq) ProtoMessage()               {}
func (*IMClientTimeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type IMClientTimeRsp struct {
	// cmd id:		0x0306
	ServerTime       *uint32 `protobuf:"varint,1,req,name=server_time,json=serverTime" json:"server_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMClientTimeRsp) Reset()                    { *m = IMClientTimeRsp{} }
func (m *IMClientTimeRsp) String() string            { return proto.CompactTextString(m) }
func (*IMClientTimeRsp) ProtoMessage()               {}
func (*IMClientTimeRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IMClientTimeRsp) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

type IMUnreadMsgCntReq struct {
	// cmd id:		0x0307
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMUnreadMsgCntReq) Reset()                    { *m = IMUnreadMsgCntReq{} }
func (m *IMUnreadMsgCntReq) String() string            { return proto.CompactTextString(m) }
func (*IMUnreadMsgCntReq) ProtoMessage()               {}
func (*IMUnreadMsgCntReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IMUnreadMsgCntReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUnreadMsgCntReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUnreadMsgCntRsp struct {
	// cmd id:		0x0308
	UserId           *uint32                     `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	TotalCnt         *uint32                     `protobuf:"varint,2,req,name=total_cnt,json=totalCnt" json:"total_cnt,omitempty"`
	UnreadinfoList   []*IM_BaseDefine.UnreadInfo `protobuf:"bytes,3,rep,name=unreadinfo_list,json=unreadinfoList" json:"unreadinfo_list,omitempty"`
	AttachData       []byte                      `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMUnreadMsgCntRsp) Reset()                    { *m = IMUnreadMsgCntRsp{} }
func (m *IMUnreadMsgCntRsp) String() string            { return proto.CompactTextString(m) }
func (*IMUnreadMsgCntRsp) ProtoMessage()               {}
func (*IMUnreadMsgCntRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IMUnreadMsgCntRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUnreadMsgCntRsp) GetTotalCnt() uint32 {
	if m != nil && m.TotalCnt != nil {
		return *m.TotalCnt
	}
	return 0
}

func (m *IMUnreadMsgCntRsp) GetUnreadinfoList() []*IM_BaseDefine.UnreadInfo {
	if m != nil {
		return m.UnreadinfoList
	}
	return nil
}

func (m *IMUnreadMsgCntRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgListReq struct {
	// cmd id:		0x0309
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	MsgIdBegin       *uint32                    `protobuf:"varint,4,req,name=msg_id_begin,json=msgIdBegin" json:"msg_id_begin,omitempty"`
	MsgCnt           *uint32                    `protobuf:"varint,5,req,name=msg_cnt,json=msgCnt" json:"msg_cnt,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgListReq) Reset()                    { *m = IMGetMsgListReq{} }
func (m *IMGetMsgListReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgListReq) ProtoMessage()               {}
func (*IMGetMsgListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IMGetMsgListReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgListReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgListReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgListReq) GetMsgIdBegin() uint32 {
	if m != nil && m.MsgIdBegin != nil {
		return *m.MsgIdBegin
	}
	return 0
}

func (m *IMGetMsgListReq) GetMsgCnt() uint32 {
	if m != nil && m.MsgCnt != nil {
		return *m.MsgCnt
	}
	return 0
}

func (m *IMGetMsgListReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 对于群而言，如果消息数目返回的数值小于请求的cnt,则表示群的消息能拉取的到头了，更早的消息没有权限拉取。
// 如果msg_cnt 和 msg_id_begin计算得到的最早消息id与实际返回的最早消息id不一致，说明服务器消息有缺失，需要
// 客户端做一个缺失标记，避免下次再次拉取。
type IMGetMsgListRsp struct {
	// cmd id:		0x030a
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	MsgIdBegin       *uint32                    `protobuf:"varint,4,req,name=msg_id_begin,json=msgIdBegin" json:"msg_id_begin,omitempty"`
	MsgList          []*IM_BaseDefine.MsgInfo   `protobuf:"bytes,5,rep,name=msg_list,json=msgList" json:"msg_list,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgListRsp) Reset()                    { *m = IMGetMsgListRsp{} }
func (m *IMGetMsgListRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgListRsp) ProtoMessage()               {}
func (*IMGetMsgListRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IMGetMsgListRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgListRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetMsgIdBegin() uint32 {
	if m != nil && m.MsgIdBegin != nil {
		return *m.MsgIdBegin
	}
	return 0
}

func (m *IMGetMsgListRsp) GetMsgList() []*IM_BaseDefine.MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetMsgListRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetLatestMsgIdReq struct {
	// cmd id: 		0x030b
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetLatestMsgIdReq) Reset()                    { *m = IMGetLatestMsgIdReq{} }
func (m *IMGetLatestMsgIdReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetLatestMsgIdReq) ProtoMessage()               {}
func (*IMGetLatestMsgIdReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IMGetLatestMsgIdReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLatestMsgIdReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetLatestMsgIdReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetLatestMsgIdReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetLatestMsgIdRsp struct {
	// cmd id:		0x030c
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	LatestMsgId      *uint32                    `protobuf:"varint,4,req,name=latest_msg_id,json=latestMsgId" json:"latest_msg_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetLatestMsgIdRsp) Reset()                    { *m = IMGetLatestMsgIdRsp{} }
func (m *IMGetLatestMsgIdRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetLatestMsgIdRsp) ProtoMessage()               {}
func (*IMGetLatestMsgIdRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IMGetLatestMsgIdRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetLatestMsgIdRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetLatestMsgId() uint32 {
	if m != nil && m.LatestMsgId != nil {
		return *m.LatestMsgId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgByIdReq struct {
	// cmd id: 		0x030d
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	MsgIdList        []uint32                   `protobuf:"varint,4,rep,name=msg_id_list,json=msgIdList" json:"msg_id_list,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgByIdReq) Reset()                    { *m = IMGetMsgByIdReq{} }
func (m *IMGetMsgByIdReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgByIdReq) ProtoMessage()               {}
func (*IMGetMsgByIdReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IMGetMsgByIdReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgByIdReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgByIdReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgByIdReq) GetMsgIdList() []uint32 {
	if m != nil {
		return m.MsgIdList
	}
	return nil
}

func (m *IMGetMsgByIdReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgByIdRsp struct {
	// cmd id:		0x030e
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	MsgList          []*IM_BaseDefine.MsgInfo   `protobuf:"bytes,4,rep,name=msg_list,json=msgList" json:"msg_list,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMGetMsgByIdRsp) Reset()                    { *m = IMGetMsgByIdRsp{} }
func (m *IMGetMsgByIdRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetMsgByIdRsp) ProtoMessage()               {}
func (*IMGetMsgByIdRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IMGetMsgByIdRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMGetMsgByIdRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMGetMsgByIdRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMGetMsgByIdRsp) GetMsgList() []*IM_BaseDefine.MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetMsgByIdRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func init() {
	proto.RegisterType((*IMMsgData)(nil), "IM.Message.IMMsgData")
	proto.RegisterType((*IMMsgDataAck)(nil), "IM.Message.IMMsgDataAck")
	proto.RegisterType((*IMMsgDataReadAck)(nil), "IM.Message.IMMsgDataReadAck")
	proto.RegisterType((*IMMsgDataReadNotify)(nil), "IM.Message.IMMsgDataReadNotify")
	proto.RegisterType((*IMClientTimeReq)(nil), "IM.Message.IMClientTimeReq")
	proto.RegisterType((*IMClientTimeRsp)(nil), "IM.Message.IMClientTimeRsp")
	proto.RegisterType((*IMUnreadMsgCntReq)(nil), "IM.Message.IMUnreadMsgCntReq")
	proto.RegisterType((*IMUnreadMsgCntRsp)(nil), "IM.Message.IMUnreadMsgCntRsp")
	proto.RegisterType((*IMGetMsgListReq)(nil), "IM.Message.IMGetMsgListReq")
	proto.RegisterType((*IMGetMsgListRsp)(nil), "IM.Message.IMGetMsgListRsp")
	proto.RegisterType((*IMGetLatestMsgIdReq)(nil), "IM.Message.IMGetLatestMsgIdReq")
	proto.RegisterType((*IMGetLatestMsgIdRsp)(nil), "IM.Message.IMGetLatestMsgIdRsp")
	proto.RegisterType((*IMGetMsgByIdReq)(nil), "IM.Message.IMGetMsgByIdReq")
	proto.RegisterType((*IMGetMsgByIdRsp)(nil), "IM.Message.IMGetMsgByIdRsp")
}

func init() { proto.RegisterFile("IM.Message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0x96, 0x73, 0xe9, 0xe5, 0x38, 0x6d, 0xff, 0xba, 0x3f, 0x34, 0x6d, 0x05, 0xb5, 0xbc, 0xca,
	0x2a, 0x12, 0xdd, 0xb3, 0x20, 0xad, 0x54, 0x2c, 0xd5, 0x2c, 0x4c, 0xbb, 0xb6, 0xa6, 0xf1, 0xb1,
	0x19, 0x88, 0x3d, 0xa9, 0xe7, 0x04, 0x29, 0xef, 0xc2, 0x02, 0x89, 0x35, 0xbc, 0x07, 0x4b, 0xf6,
	0x2c, 0x79, 0x08, 0x56, 0x08, 0xcd, 0x8c, 0x4b, 0x1a, 0xf7, 0xe2, 0x22, 0x21, 0xa5, 0xbb, 0xe4,
	0x5c, 0x26, 0xdf, 0x6d, 0x46, 0x81, 0xff, 0xfc, 0xa0, 0x1f, 0xa0, 0x94, 0x2c, 0xc5, 0xfe, 0xb8,
	0x10, 0x24, 0x1c, 0x98, 0x55, 0x76, 0xb7, 0xfc, 0xa0, 0x3f, 0x60, 0x12, 0x8f, 0x30, 0xe1, 0x79,
	0x39, 0xe0, 0xfd, 0xb4, 0x60, 0xd5, 0x0f, 0x02, 0x99, 0x1e, 0x31, 0x62, 0x8e, 0x0b, 0x9d, 0xa4,
	0x10, 0x59, 0x34, 0x91, 0x58, 0x44, 0x3c, 0xee, 0x5a, 0x6e, 0xa3, 0xb7, 0x16, 0x82, 0xaa, 0x9d,
	0x49, 0x2c, 0xfc, 0xd8, 0xf1, 0x60, 0x8d, 0x44, 0x24, 0x51, 0x4a, 0x2e, 0x72, 0x35, 0xd2, 0xd0,
	0x23, 0x36, 0x89, 0xd7, 0xa6, 0xe6, 0xc7, 0xce, 0x23, 0x58, 0xca, 0x64, 0xaa, 0x9a, 0x4d, 0xdd,
	0x6c, 0x67, 0x32, 0xf5, 0x63, 0x67, 0x1f, 0xec, 0x61, 0x81, 0x8c, 0x30, 0x22, 0x9e, 0x61, 0xb7,
	0x65, 0xce, 0x36, 0xa5, 0x53, 0x9e, 0xa1, 0xf3, 0x0c, 0x56, 0xd4, 0x1e, 0x4d, 0xc7, 0xd8, 0x6d,
	0xbb, 0x8d, 0xde, 0xfa, 0xc1, 0xe3, 0xfe, 0x3c, 0xe6, 0x40, 0xa6, 0xa7, 0xd3, 0x31, 0x86, 0xcb,
	0x99, 0xf9, 0xe0, 0xec, 0x98, 0x95, 0x98, 0x11, 0xeb, 0x2e, 0xb9, 0x8d, 0x5e, 0x47, 0xb7, 0x34,
	0x97, 0x7d, 0xb0, 0x19, 0x11, 0x1b, 0xbe, 0x31, 0xdd, 0xff, 0x5d, 0xab, 0xd7, 0x09, 0xc1, 0x94,
	0xd4, 0x80, 0xf7, 0xc1, 0x82, 0xce, 0x1f, 0xea, 0x2f, 0x86, 0xef, 0x9c, 0x6d, 0x58, 0x9e, 0x27,
	0xbe, 0x34, 0x31, 0xa4, 0x9f, 0x00, 0x5c, 0x63, 0xbc, 0x2a, 0xeb, 0xf8, 0x3e, 0x87, 0xce, 0xe5,
	0x96, 0xa6, 0xd4, 0xd2, 0x94, 0x76, 0x2b, 0x94, 0x4a, 0xd9, 0x34, 0x2d, 0x5b, 0xce, 0xbe, 0x78,
	0x1f, 0x2d, 0xe5, 0x67, 0x09, 0x2f, 0x44, 0x16, 0x3f, 0x3c, 0x88, 0x9f, 0x2c, 0xd8, 0x9a, 0x83,
	0xf8, 0x4a, 0x10, 0x4f, 0xa6, 0x0f, 0x0c, 0xe5, 0x26, 0x6c, 0xf8, 0xc1, 0xe1, 0x88, 0x63, 0x4e,
	0x2a, 0x66, 0x21, 0x5e, 0x78, 0x07, 0x95, 0x92, 0x1c, 0xab, 0xb8, 0x48, 0x2c, 0xde, 0x63, 0x61,
	0xd2, 0x59, 0x26, 0xdf, 0x94, 0xd4, 0x8c, 0x17, 0xc0, 0xa6, 0x1f, 0x9c, 0xe5, 0x05, 0xb2, 0x38,
	0x90, 0xe9, 0x61, 0x4e, 0x21, 0x5e, 0xdc, 0xce, 0xb4, 0x36, 0x7d, 0x5f, 0xac, 0x6b, 0xe7, 0xc9,
	0xf1, 0xed, 0xe7, 0xed, 0xc1, 0x2a, 0x09, 0x62, 0xa3, 0x68, 0x98, 0x53, 0x29, 0xdc, 0x8a, 0x2e,
	0x1c, 0xe6, 0xe4, 0x0c, 0x60, 0x63, 0xa2, 0x0f, 0xe2, 0x79, 0x22, 0xa2, 0x11, 0x97, 0xd4, 0x6d,
	0xba, 0xcd, 0x9e, 0x7d, 0xb0, 0x53, 0xd1, 0xc8, 0xfc, 0x9c, 0x9f, 0x27, 0x22, 0x5c, 0x9f, 0x6d,
	0x9c, 0x70, 0x49, 0xf5, 0x80, 0x7f, 0x58, 0x4a, 0xb4, 0x63, 0xa4, 0x40, 0xa6, 0x6a, 0xe3, 0x4e,
	0xfa, 0x55, 0xcb, 0x1a, 0x7f, 0x65, 0x59, 0x25, 0x27, 0xcd, 0x6a, 0x4e, 0x5c, 0xe8, 0x98, 0x9c,
	0x44, 0xe7, 0x98, 0xf2, 0xfc, 0xf2, 0x29, 0xd1, 0x69, 0x19, 0xa8, 0x8a, 0x02, 0xa6, 0x26, 0x94,
	0x58, 0x6d, 0x03, 0x2c, 0xd3, 0x1a, 0xd7, 0xd3, 0xfc, 0x55, 0xa5, 0x79, 0x97, 0x2b, 0x8b, 0xa6,
	0x59, 0xbe, 0x98, 0xda, 0xf1, 0xb6, 0x76, 0xfc, 0x86, 0x17, 0x53, 0xdb, 0xad, 0xe4, 0xb8, 0x9f,
	0xcf, 0x9f, 0xf5, 0xa5, 0x3e, 0x46, 0x3a, 0x61, 0x84, 0x52, 0xc9, 0xe0, 0xc7, 0x0b, 0xf4, 0xba,
	0x16, 0xef, 0xb7, 0x9b, 0xf0, 0x2e, 0xce, 0x34, 0x0f, 0xd6, 0x46, 0x1a, 0x48, 0x54, 0x3e, 0x65,
	0xc6, 0x35, 0x7b, 0x34, 0x43, 0x57, 0xcf, 0xe9, 0xeb, 0x95, 0x10, 0x0e, 0xa6, 0x0b, 0xd5, 0xff,
	0x29, 0xd8, 0x65, 0x08, 0x75, 0xca, 0x5a, 0x6e, 0x53, 0xf5, 0x75, 0x06, 0xef, 0x97, 0xa7, 0xef,
	0x55, 0x2e, 0x8b, 0xf3, 0xe6, 0xea, 0x75, 0x69, 0xfd, 0x9b, 0xeb, 0x32, 0xd8, 0x83, 0xed, 0xa1,
	0xc8, 0xfa, 0x99, 0x48, 0x27, 0x6f, 0x39, 0xf6, 0x89, 0xcc, 0x1f, 0xab, 0xf3, 0x49, 0xf2, 0xb2,
	0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x93, 0xe4, 0xa6, 0x51, 0x91, 0x09, 0x00, 0x00,
}
