// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IM.Login.proto

/*
Package IM_Login is a generated protocol buffer package.

It is generated from these files:
	IM.Login.proto

It has these top-level messages:
	IMMsgServReq
	IMMsgServRsp
	IMLoginReq
	IMLoginRes
	IMLogoutReq
	IMLogoutRsp
	IMKickUser
	IMDeviceTokenReq
	IMDeviceTokenRsp
	IMKickPCClientReq
	IMKickPCClientRsp
	IMPushShieldReq
	IMPushShieldRsp
	IMQueryPushShieldReq
	IMQueryPushShieldRsp
*/
package IM_Login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import IM_BaseDefine "github.com/xiaominfc/xiny/pb/IM_BaseDefine"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IMMsgServReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IMMsgServReq) Reset()                    { *m = IMMsgServReq{} }
func (m *IMMsgServReq) String() string            { return proto.CompactTextString(m) }
func (*IMMsgServReq) ProtoMessage()               {}
func (*IMMsgServReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type IMMsgServRsp struct {
	// cmd id:		0x0102
	ResultCode       *IM_BaseDefine.ResultType `protobuf:"varint,1,req,name=result_code,json=resultCode,enum=IM.BaseDefine.ResultType" json:"result_code,omitempty"`
	PriorIp          *string                   `protobuf:"bytes,2,opt,name=prior_ip,json=priorIp" json:"prior_ip,omitempty"`
	BackipIp         *string                   `protobuf:"bytes,3,opt,name=backip_ip,json=backipIp" json:"backip_ip,omitempty"`
	Port             *uint32                   `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMMsgServRsp) Reset()                    { *m = IMMsgServRsp{} }
func (m *IMMsgServRsp) String() string            { return proto.CompactTextString(m) }
func (*IMMsgServRsp) ProtoMessage()               {}
func (*IMMsgServRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMMsgServRsp) GetResultCode() IM_BaseDefine.ResultType {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return IM_BaseDefine.ResultType_REFUSE_REASON_NONE
}

func (m *IMMsgServRsp) GetPriorIp() string {
	if m != nil && m.PriorIp != nil {
		return *m.PriorIp
	}
	return ""
}

func (m *IMMsgServRsp) GetBackipIp() string {
	if m != nil && m.BackipIp != nil {
		return *m.BackipIp
	}
	return ""
}

func (m *IMMsgServRsp) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type IMLoginReq struct {
	// cmd id:		0x0103
	UserName         *string                     `protobuf:"bytes,1,req,name=user_name,json=userName" json:"user_name,omitempty"`
	Password         *string                     `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	OnlineStatus     *IM_BaseDefine.UserStatType `protobuf:"varint,3,req,name=online_status,json=onlineStatus,enum=IM.BaseDefine.UserStatType" json:"online_status,omitempty"`
	ClientType       *IM_BaseDefine.ClientType   `protobuf:"varint,4,req,name=client_type,json=clientType,enum=IM.BaseDefine.ClientType" json:"client_type,omitempty"`
	ClientVersion    *string                     `protobuf:"bytes,5,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMLoginReq) Reset()                    { *m = IMLoginReq{} }
func (m *IMLoginReq) String() string            { return proto.CompactTextString(m) }
func (*IMLoginReq) ProtoMessage()               {}
func (*IMLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IMLoginReq) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *IMLoginReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *IMLoginReq) GetOnlineStatus() IM_BaseDefine.UserStatType {
	if m != nil && m.OnlineStatus != nil {
		return *m.OnlineStatus
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

func (m *IMLoginReq) GetClientType() IM_BaseDefine.ClientType {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return IM_BaseDefine.ClientType_CLIENT_TYPE_WINDOWS
}

func (m *IMLoginReq) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

type IMLoginRes struct {
	// cmd id:		0x0104
	ServerTime       *uint32                     `protobuf:"varint,1,req,name=server_time,json=serverTime" json:"server_time,omitempty"`
	ResultCode       *IM_BaseDefine.ResultType   `protobuf:"varint,2,req,name=result_code,json=resultCode,enum=IM.BaseDefine.ResultType" json:"result_code,omitempty"`
	ResultString     *string                     `protobuf:"bytes,3,opt,name=result_string,json=resultString" json:"result_string,omitempty"`
	OnlineStatus     *IM_BaseDefine.UserStatType `protobuf:"varint,4,opt,name=online_status,json=onlineStatus,enum=IM.BaseDefine.UserStatType" json:"online_status,omitempty"`
	UserInfo         *IM_BaseDefine.UserInfo     `protobuf:"bytes,5,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMLoginRes) Reset()                    { *m = IMLoginRes{} }
func (m *IMLoginRes) String() string            { return proto.CompactTextString(m) }
func (*IMLoginRes) ProtoMessage()               {}
func (*IMLoginRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IMLoginRes) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *IMLoginRes) GetResultCode() IM_BaseDefine.ResultType {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return IM_BaseDefine.ResultType_REFUSE_REASON_NONE
}

func (m *IMLoginRes) GetResultString() string {
	if m != nil && m.ResultString != nil {
		return *m.ResultString
	}
	return ""
}

func (m *IMLoginRes) GetOnlineStatus() IM_BaseDefine.UserStatType {
	if m != nil && m.OnlineStatus != nil {
		return *m.OnlineStatus
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

func (m *IMLoginRes) GetUserInfo() *IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type IMLogoutReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *IMLogoutReq) Reset()                    { *m = IMLogoutReq{} }
func (m *IMLogoutReq) String() string            { return proto.CompactTextString(m) }
func (*IMLogoutReq) ProtoMessage()               {}
func (*IMLogoutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type IMLogoutRsp struct {
	// cmd id:		0x0106
	ResultCode       *uint32 `protobuf:"varint,1,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMLogoutRsp) Reset()                    { *m = IMLogoutRsp{} }
func (m *IMLogoutRsp) String() string            { return proto.CompactTextString(m) }
func (*IMLogoutRsp) ProtoMessage()               {}
func (*IMLogoutRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IMLogoutRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

type IMKickUser struct {
	// cmd id:		0x0107
	UserId           *uint32                       `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	KickReason       *IM_BaseDefine.KickReasonType `protobuf:"varint,2,req,name=kick_reason,json=kickReason,enum=IM.BaseDefine.KickReasonType" json:"kick_reason,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *IMKickUser) Reset()                    { *m = IMKickUser{} }
func (m *IMKickUser) String() string            { return proto.CompactTextString(m) }
func (*IMKickUser) ProtoMessage()               {}
func (*IMKickUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IMKickUser) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMKickUser) GetKickReason() IM_BaseDefine.KickReasonType {
	if m != nil && m.KickReason != nil {
		return *m.KickReason
	}
	return IM_BaseDefine.KickReasonType_KICK_REASON_DUPLICATE_USER
}

type IMDeviceTokenReq struct {
	// cmd id:		0x0108
	UserId           *uint32                   `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	DeviceToken      *string                   `protobuf:"bytes,2,req,name=device_token,json=deviceToken" json:"device_token,omitempty"`
	ClientType       *IM_BaseDefine.ClientType `protobuf:"varint,3,opt,name=client_type,json=clientType,enum=IM.BaseDefine.ClientType" json:"client_type,omitempty"`
	AttachData       []byte                    `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMDeviceTokenReq) Reset()                    { *m = IMDeviceTokenReq{} }
func (m *IMDeviceTokenReq) String() string            { return proto.CompactTextString(m) }
func (*IMDeviceTokenReq) ProtoMessage()               {}
func (*IMDeviceTokenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IMDeviceTokenReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDeviceTokenReq) GetDeviceToken() string {
	if m != nil && m.DeviceToken != nil {
		return *m.DeviceToken
	}
	return ""
}

func (m *IMDeviceTokenReq) GetClientType() IM_BaseDefine.ClientType {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return IM_BaseDefine.ClientType_CLIENT_TYPE_WINDOWS
}

func (m *IMDeviceTokenReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMDeviceTokenRsp struct {
	// cmd id: 		0x0109
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMDeviceTokenRsp) Reset()                    { *m = IMDeviceTokenRsp{} }
func (m *IMDeviceTokenRsp) String() string            { return proto.CompactTextString(m) }
func (*IMDeviceTokenRsp) ProtoMessage()               {}
func (*IMDeviceTokenRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IMDeviceTokenRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDeviceTokenRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 只给移动端请求
type IMKickPCClientReq struct {
	// cmd id:		0x010a
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMKickPCClientReq) Reset()                    { *m = IMKickPCClientReq{} }
func (m *IMKickPCClientReq) String() string            { return proto.CompactTextString(m) }
func (*IMKickPCClientReq) ProtoMessage()               {}
func (*IMKickPCClientReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IMKickPCClientReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type IMKickPCClientRsp struct {
	// cmd id: 		0x010b
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode       *uint32 `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMKickPCClientRsp) Reset()                    { *m = IMKickPCClientRsp{} }
func (m *IMKickPCClientRsp) String() string            { return proto.CompactTextString(m) }
func (*IMKickPCClientRsp) ProtoMessage()               {}
func (*IMKickPCClientRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IMKickPCClientRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMKickPCClientRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

// 一旦设置以后，22:00 -- 07:00不发送
type IMPushShieldReq struct {
	// cmd id:			0x010c
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ShieldStatus     *uint32 `protobuf:"varint,2,req,name=shield_status,json=shieldStatus" json:"shield_status,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMPushShieldReq) Reset()                    { *m = IMPushShieldReq{} }
func (m *IMPushShieldReq) String() string            { return proto.CompactTextString(m) }
func (*IMPushShieldReq) ProtoMessage()               {}
func (*IMPushShieldReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IMPushShieldReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMPushShieldReq) GetShieldStatus() uint32 {
	if m != nil && m.ShieldStatus != nil {
		return *m.ShieldStatus
	}
	return 0
}

func (m *IMPushShieldReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMPushShieldRsp struct {
	// cmd id:			0x010d
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode       *uint32 `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	ShieldStatus     *uint32 `protobuf:"varint,3,opt,name=shield_status,json=shieldStatus" json:"shield_status,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMPushShieldRsp) Reset()                    { *m = IMPushShieldRsp{} }
func (m *IMPushShieldRsp) String() string            { return proto.CompactTextString(m) }
func (*IMPushShieldRsp) ProtoMessage()               {}
func (*IMPushShieldRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IMPushShieldRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMPushShieldRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMPushShieldRsp) GetShieldStatus() uint32 {
	if m != nil && m.ShieldStatus != nil {
		return *m.ShieldStatus
	}
	return 0
}

func (m *IMPushShieldRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 如果用户重新安装app，第一次启动登录成功后，app主动查询
// 服务端返回IMQueryPushShieldRsp
type IMQueryPushShieldReq struct {
	// cmd id:			0x010e
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMQueryPushShieldReq) Reset()                    { *m = IMQueryPushShieldReq{} }
func (m *IMQueryPushShieldReq) String() string            { return proto.CompactTextString(m) }
func (*IMQueryPushShieldReq) ProtoMessage()               {}
func (*IMQueryPushShieldReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IMQueryPushShieldReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMQueryPushShieldReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMQueryPushShieldRsp struct {
	// cmd id:			0x010f
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode       *uint32 `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	ShieldStatus     *uint32 `protobuf:"varint,3,opt,name=shield_status,json=shieldStatus" json:"shield_status,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMQueryPushShieldRsp) Reset()                    { *m = IMQueryPushShieldRsp{} }
func (m *IMQueryPushShieldRsp) String() string            { return proto.CompactTextString(m) }
func (*IMQueryPushShieldRsp) ProtoMessage()               {}
func (*IMQueryPushShieldRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *IMQueryPushShieldRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMQueryPushShieldRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMQueryPushShieldRsp) GetShieldStatus() uint32 {
	if m != nil && m.ShieldStatus != nil {
		return *m.ShieldStatus
	}
	return 0
}

func (m *IMQueryPushShieldRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func init() {
	proto.RegisterType((*IMMsgServReq)(nil), "IM.Login.IMMsgServReq")
	proto.RegisterType((*IMMsgServRsp)(nil), "IM.Login.IMMsgServRsp")
	proto.RegisterType((*IMLoginReq)(nil), "IM.Login.IMLoginReq")
	proto.RegisterType((*IMLoginRes)(nil), "IM.Login.IMLoginRes")
	proto.RegisterType((*IMLogoutReq)(nil), "IM.Login.IMLogoutReq")
	proto.RegisterType((*IMLogoutRsp)(nil), "IM.Login.IMLogoutRsp")
	proto.RegisterType((*IMKickUser)(nil), "IM.Login.IMKickUser")
	proto.RegisterType((*IMDeviceTokenReq)(nil), "IM.Login.IMDeviceTokenReq")
	proto.RegisterType((*IMDeviceTokenRsp)(nil), "IM.Login.IMDeviceTokenRsp")
	proto.RegisterType((*IMKickPCClientReq)(nil), "IM.Login.IMKickPCClientReq")
	proto.RegisterType((*IMKickPCClientRsp)(nil), "IM.Login.IMKickPCClientRsp")
	proto.RegisterType((*IMPushShieldReq)(nil), "IM.Login.IMPushShieldReq")
	proto.RegisterType((*IMPushShieldRsp)(nil), "IM.Login.IMPushShieldRsp")
	proto.RegisterType((*IMQueryPushShieldReq)(nil), "IM.Login.IMQueryPushShieldReq")
	proto.RegisterType((*IMQueryPushShieldRsp)(nil), "IM.Login.IMQueryPushShieldRsp")
}

func init() { proto.RegisterFile("IM.Login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x93, 0x42, 0xd3, 0x71, 0x1c, 0xc0, 0x54, 0xaa, 0xdb, 0x0a, 0x35, 0xb8, 0x42, 0xca,
	0x01, 0xf9, 0x50, 0x71, 0xe2, 0x80, 0x50, 0xdb, 0x03, 0x16, 0x35, 0x2a, 0x4e, 0xe1, 0x6a, 0x6d,
	0xed, 0x49, 0xba, 0x38, 0xf1, 0x6e, 0x77, 0xd7, 0x41, 0x7d, 0x01, 0xee, 0x5c, 0xfa, 0x12, 0xbc,
	0x19, 0x4f, 0x81, 0xbc, 0xeb, 0x96, 0xd4, 0xfd, 0x49, 0x2b, 0x0e, 0xdc, 0x76, 0xbe, 0x9d, 0x99,
	0x9d, 0xef, 0x9b, 0x4f, 0x36, 0xf4, 0xc2, 0x28, 0x38, 0x60, 0x63, 0x5a, 0x04, 0x5c, 0x30, 0xc5,
	0xdc, 0xce, 0x45, 0xbc, 0xf1, 0x3c, 0x8c, 0x82, 0x5d, 0x22, 0x71, 0x1f, 0x47, 0xb4, 0x40, 0x73,
	0xed, 0xf7, 0xa0, 0x1b, 0x46, 0x91, 0x1c, 0x0f, 0x51, 0xcc, 0x62, 0x3c, 0xf5, 0xcf, 0xad, 0x79,
	0x40, 0x72, 0xf7, 0x2d, 0xd8, 0x02, 0x65, 0x39, 0x51, 0x49, 0xca, 0x32, 0xf4, 0xac, 0x7e, 0x6b,
	0xd0, 0xdb, 0x59, 0x0f, 0xae, 0xf6, 0x8a, 0x75, 0xc6, 0xd1, 0x19, 0xc7, 0x18, 0x4c, 0xf6, 0x1e,
	0xcb, 0xd0, 0x5d, 0x87, 0x0e, 0x17, 0x94, 0x89, 0x84, 0x72, 0xaf, 0xd5, 0xb7, 0x06, 0x2b, 0xf1,
	0xb2, 0x8e, 0x43, 0xee, 0x6e, 0xc2, 0xca, 0x31, 0x49, 0x73, 0xca, 0xab, 0xbb, 0xb6, 0xbe, 0xeb,
	0x18, 0x20, 0xe4, 0xae, 0x0b, 0x4b, 0x9c, 0x09, 0xe5, 0x2d, 0xf5, 0xad, 0x81, 0x13, 0xeb, 0xb3,
	0xff, 0xdb, 0x02, 0x08, 0x23, 0xcd, 0x24, 0xc6, 0xd3, 0xaa, 0xbe, 0x94, 0x28, 0x92, 0x82, 0x4c,
	0xcd, 0x50, 0x2b, 0x71, 0xa7, 0x02, 0x3e, 0x91, 0x29, 0xba, 0x1b, 0xd0, 0xe1, 0x44, 0xca, 0xef,
	0x4c, 0x64, 0x5e, 0xcb, 0xdc, 0x5d, 0xc4, 0xee, 0x7b, 0x70, 0x58, 0x31, 0xa1, 0x05, 0x26, 0x52,
	0x11, 0x55, 0x4a, 0xaf, 0xad, 0x19, 0x6d, 0x36, 0x18, 0x7d, 0x91, 0x28, 0x86, 0x8a, 0x18, 0x4e,
	0x5d, 0x53, 0x31, 0xd4, 0x05, 0x95, 0x22, 0xe9, 0x84, 0x62, 0xa1, 0x12, 0x75, 0xc6, 0xd1, 0x5b,
	0xba, 0x51, 0x91, 0x3d, 0x9d, 0x61, 0x14, 0x49, 0x2f, 0xcf, 0xee, 0x2b, 0xe8, 0xd5, 0xb5, 0x33,
	0x14, 0x92, 0xb2, 0xc2, 0x7b, 0xa4, 0xb9, 0x3b, 0x06, 0xfd, 0x6a, 0x40, 0xff, 0x47, 0x6b, 0x8e,
	0xac, 0x74, 0xb7, 0xc0, 0x96, 0x28, 0x66, 0x28, 0x12, 0x45, 0x6b, 0xba, 0x4e, 0x0c, 0x06, 0x3a,
	0xa2, 0x53, 0x6c, 0x2e, 0xa9, 0xf5, 0x90, 0x25, 0x6d, 0x83, 0x53, 0xd7, 0x4a, 0x25, 0x68, 0x31,
	0xae, 0xb7, 0xd1, 0x35, 0xe0, 0x50, 0x63, 0xd7, 0x55, 0xab, 0x56, 0xf3, 0x20, 0xd5, 0xde, 0xd4,
	0x0b, 0xa3, 0xc5, 0x88, 0x69, 0xd2, 0xf6, 0xce, 0xda, 0x0d, 0xd5, 0x61, 0x31, 0x62, 0x66, 0x93,
	0xd5, 0xc9, 0x77, 0xc0, 0xd6, 0x3a, 0xb0, 0x52, 0x55, 0xee, 0x0c, 0xe6, 0x42, 0xc9, 0x2b, 0x5d,
	0x9a, 0xde, 0x74, 0xe6, 0xb9, 0xf9, 0x58, 0xc9, 0xf8, 0x91, 0xa6, 0x79, 0xd5, 0xda, 0x5d, 0x83,
	0x65, 0x33, 0x42, 0x56, 0xa7, 0x3e, 0xd6, 0xef, 0x64, 0xee, 0x3b, 0xb0, 0x73, 0x9a, 0xe6, 0x89,
	0x40, 0x22, 0x59, 0x51, 0xcb, 0xf7, 0xa2, 0x31, 0x5d, 0xd5, 0x26, 0xd6, 0x09, 0x46, 0xc2, 0xfc,
	0x32, 0xf6, 0x7f, 0x59, 0xf0, 0x34, 0x8c, 0xf6, 0x71, 0x46, 0x53, 0x3c, 0x62, 0x39, 0x6a, 0x87,
	0xde, 0xfa, 0xda, 0x4b, 0xe8, 0x66, 0x3a, 0x35, 0x51, 0x55, 0x6e, 0xed, 0x50, 0x3b, 0xfb, 0x5b,
	0xde, 0xb4, 0x58, 0x5b, 0x8b, 0x7d, 0x4f, 0x8b, 0x6d, 0x81, 0x4d, 0x94, 0x22, 0xe9, 0x49, 0x92,
	0x11, 0x45, 0xbc, 0xd5, 0xbe, 0x35, 0xe8, 0xc6, 0x60, 0xa0, 0x7d, 0xa2, 0x88, 0x7f, 0xd0, 0x1c,
	0x56, 0xf2, 0xdb, 0x87, 0x5d, 0xd8, 0xed, 0x35, 0x3c, 0x33, 0x12, 0x1f, 0xee, 0x99, 0x81, 0xee,
	0xe2, 0xee, 0x47, 0xd7, 0xb2, 0x17, 0x3c, 0xde, 0xb4, 0xf5, 0xd5, 0xfd, 0x72, 0x78, 0x12, 0x46,
	0x87, 0xa5, 0x3c, 0x19, 0x9e, 0x50, 0x9c, 0x64, 0x77, 0xca, 0xbe, 0x0d, 0x8e, 0xd4, 0x59, 0x17,
	0x16, 0x36, 0xed, 0xba, 0x06, 0xac, 0x5d, 0xba, 0x90, 0xee, 0x4f, 0xab, 0xf1, 0xe4, 0xbf, 0xcc,
	0x7f, 0x7d, 0xa6, 0xb6, 0xfe, 0xe2, 0x3d, 0x70, 0xa6, 0x43, 0x58, 0x0d, 0xa3, 0xcf, 0x25, 0x8a,
	0xb3, 0x7b, 0x4a, 0xb1, 0xb0, 0xe3, 0xb9, 0x75, 0x53, 0xcb, 0xff, 0x4f, 0x75, 0x77, 0x13, 0xd6,
	0x52, 0x36, 0x0d, 0xa6, 0x6c, 0x5c, 0x7e, 0xa3, 0x18, 0x28, 0x65, 0x7e, 0x63, 0xc7, 0xe5, 0xe8,
	0x43, 0xfb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x65, 0x52, 0x70, 0xfb, 0x06, 0x00, 0x00,
}
