// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IM.Buddy.proto

/*
Package IM_Buddy is a generated protocol buffer package.

It is generated from these files:
	IM.Buddy.proto

It has these top-level messages:
	IMRecentContactSessionReq
	IMRecentContactSessionRsp
	IMUserStatNotify
	IMUsersInfoReq
	IMUsersInfoRsp
	IMRemoveSessionReq
	IMRemoveSessionRsp
	IMAllUserReq
	IMAllUserRsp
	IMUsersStatReq
	IMUsersStatRsp
	IMChangeAvatarReq
	IMChangeAvatarRsp
	IMPCLoginStatusNotify
	IMRemoveSessionNotify
	IMDepartmentReq
	IMDepartmentRsp
	IMAvatarChangedNotify
	IMChangeSignInfoReq
	IMChangeSignInfoRsp
	IMSignInfoChangedNotify
*/
package IM_Buddy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import IM_BaseDefine "github.com/xiaominfc/xiny/pb/IM_BaseDefine"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IMRecentContactSessionReq struct {
	// cmd id:		0x0201
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime *uint32 `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMRecentContactSessionReq) Reset()                    { *m = IMRecentContactSessionReq{} }
func (m *IMRecentContactSessionReq) String() string            { return proto.CompactTextString(m) }
func (*IMRecentContactSessionReq) ProtoMessage()               {}
func (*IMRecentContactSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IMRecentContactSessionReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRecentContactSessionReq) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMRecentContactSessionReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRecentContactSessionRsp struct {
	// cmd id:		0x0202
	UserId             *uint32                             `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ContactSessionList []*IM_BaseDefine.ContactSessionInfo `protobuf:"bytes,2,rep,name=contact_session_list,json=contactSessionList" json:"contact_session_list,omitempty"`
	AttachData         []byte                              `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized   []byte                              `json:"-"`
}

func (m *IMRecentContactSessionRsp) Reset()                    { *m = IMRecentContactSessionRsp{} }
func (m *IMRecentContactSessionRsp) String() string            { return proto.CompactTextString(m) }
func (*IMRecentContactSessionRsp) ProtoMessage()               {}
func (*IMRecentContactSessionRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IMRecentContactSessionRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRecentContactSessionRsp) GetContactSessionList() []*IM_BaseDefine.ContactSessionInfo {
	if m != nil {
		return m.ContactSessionList
	}
	return nil
}

func (m *IMRecentContactSessionRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUserStatNotify struct {
	// cmd id:		0x0203
	UserStat         *IM_BaseDefine.UserStat `protobuf:"bytes,1,req,name=user_stat,json=userStat" json:"user_stat,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *IMUserStatNotify) Reset()                    { *m = IMUserStatNotify{} }
func (m *IMUserStatNotify) String() string            { return proto.CompactTextString(m) }
func (*IMUserStatNotify) ProtoMessage()               {}
func (*IMUserStatNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IMUserStatNotify) GetUserStat() *IM_BaseDefine.UserStat {
	if m != nil {
		return m.UserStat
	}
	return nil
}

type IMUsersInfoReq struct {
	// cmd id:		0x0204
	UserId           *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserIdList       []uint32 `protobuf:"varint,2,rep,name=user_id_list,json=userIdList" json:"user_id_list,omitempty"`
	AttachData       []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IMUsersInfoReq) Reset()                    { *m = IMUsersInfoReq{} }
func (m *IMUsersInfoReq) String() string            { return proto.CompactTextString(m) }
func (*IMUsersInfoReq) ProtoMessage()               {}
func (*IMUsersInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IMUsersInfoReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersInfoReq) GetUserIdList() []uint32 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

func (m *IMUsersInfoReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUsersInfoRsp struct {
	// cmd id:		0x0205
	UserId           *uint32                   `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserInfoList     []*IM_BaseDefine.UserInfo `protobuf:"bytes,2,rep,name=user_info_list,json=userInfoList" json:"user_info_list,omitempty"`
	AttachData       []byte                    `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMUsersInfoRsp) Reset()                    { *m = IMUsersInfoRsp{} }
func (m *IMUsersInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*IMUsersInfoRsp) ProtoMessage()               {}
func (*IMUsersInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IMUsersInfoRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersInfoRsp) GetUserInfoList() []*IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserInfoList
	}
	return nil
}

func (m *IMUsersInfoRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRemoveSessionReq struct {
	// cmd id:		0x0206
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMRemoveSessionReq) Reset()                    { *m = IMRemoveSessionReq{} }
func (m *IMRemoveSessionReq) String() string            { return proto.CompactTextString(m) }
func (*IMRemoveSessionReq) ProtoMessage()               {}
func (*IMRemoveSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IMRemoveSessionReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRemoveSessionReq) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMRemoveSessionReq) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMRemoveSessionReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMRemoveSessionRsp struct {
	// cmd id:		0x0207
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode       *uint32                    `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,3,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,4,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AttachData       []byte                     `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMRemoveSessionRsp) Reset()                    { *m = IMRemoveSessionRsp{} }
func (m *IMRemoveSessionRsp) String() string            { return proto.CompactTextString(m) }
func (*IMRemoveSessionRsp) ProtoMessage()               {}
func (*IMRemoveSessionRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IMRemoveSessionRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRemoveSessionRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMRemoveSessionRsp) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMRemoveSessionRsp) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *IMRemoveSessionRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMAllUserReq struct {
	// cmd id:		0x0208
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime *uint32 `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMAllUserReq) Reset()                    { *m = IMAllUserReq{} }
func (m *IMAllUserReq) String() string            { return proto.CompactTextString(m) }
func (*IMAllUserReq) ProtoMessage()               {}
func (*IMAllUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IMAllUserReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMAllUserReq) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMAllUserReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMAllUserRsp struct {
	// cmd id:		0x0209
	UserId           *uint32                   `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime *uint32                   `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	UserList         []*IM_BaseDefine.UserInfo `protobuf:"bytes,3,rep,name=user_list,json=userList" json:"user_list,omitempty"`
	AttachData       []byte                    `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMAllUserRsp) Reset()                    { *m = IMAllUserRsp{} }
func (m *IMAllUserRsp) String() string            { return proto.CompactTextString(m) }
func (*IMAllUserRsp) ProtoMessage()               {}
func (*IMAllUserRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *IMAllUserRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMAllUserRsp) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMAllUserRsp) GetUserList() []*IM_BaseDefine.UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *IMAllUserRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUsersStatReq struct {
	// cmd id:		0x020a
	UserId           *uint32  `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserIdList       []uint32 `protobuf:"varint,2,rep,name=user_id_list,json=userIdList" json:"user_id_list,omitempty"`
	AttachData       []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IMUsersStatReq) Reset()                    { *m = IMUsersStatReq{} }
func (m *IMUsersStatReq) String() string            { return proto.CompactTextString(m) }
func (*IMUsersStatReq) ProtoMessage()               {}
func (*IMUsersStatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IMUsersStatReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersStatReq) GetUserIdList() []uint32 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

func (m *IMUsersStatReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUsersStatRsp struct {
	// cmd id:		0x020b
	UserId           *uint32                   `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserStatList     []*IM_BaseDefine.UserStat `protobuf:"bytes,2,rep,name=user_stat_list,json=userStatList" json:"user_stat_list,omitempty"`
	AttachData       []byte                    `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *IMUsersStatRsp) Reset()                    { *m = IMUsersStatRsp{} }
func (m *IMUsersStatRsp) String() string            { return proto.CompactTextString(m) }
func (*IMUsersStatRsp) ProtoMessage()               {}
func (*IMUsersStatRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IMUsersStatRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMUsersStatRsp) GetUserStatList() []*IM_BaseDefine.UserStat {
	if m != nil {
		return m.UserStatList
	}
	return nil
}

func (m *IMUsersStatRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMChangeAvatarReq struct {
	// cmd id:		0x020c
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	AvatarUrl        *string `protobuf:"bytes,2,req,name=avatar_url,json=avatarUrl" json:"avatar_url,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMChangeAvatarReq) Reset()                    { *m = IMChangeAvatarReq{} }
func (m *IMChangeAvatarReq) String() string            { return proto.CompactTextString(m) }
func (*IMChangeAvatarReq) ProtoMessage()               {}
func (*IMChangeAvatarReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IMChangeAvatarReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeAvatarReq) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

func (m *IMChangeAvatarReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMChangeAvatarRsp struct {
	// cmd id:		0x020d
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode       *uint32 `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMChangeAvatarRsp) Reset()                    { *m = IMChangeAvatarRsp{} }
func (m *IMChangeAvatarRsp) String() string            { return proto.CompactTextString(m) }
func (*IMChangeAvatarRsp) ProtoMessage()               {}
func (*IMChangeAvatarRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IMChangeAvatarRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeAvatarRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMChangeAvatarRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 只给移动端通知
type IMPCLoginStatusNotify struct {
	// cmd id:		0x020e
	UserId           *uint32                     `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LoginStat        *IM_BaseDefine.UserStatType `protobuf:"varint,2,req,name=login_stat,json=loginStat,enum=IM.BaseDefine.UserStatType" json:"login_stat,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMPCLoginStatusNotify) Reset()                    { *m = IMPCLoginStatusNotify{} }
func (m *IMPCLoginStatusNotify) String() string            { return proto.CompactTextString(m) }
func (*IMPCLoginStatusNotify) ProtoMessage()               {}
func (*IMPCLoginStatusNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *IMPCLoginStatusNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMPCLoginStatusNotify) GetLoginStat() IM_BaseDefine.UserStatType {
	if m != nil && m.LoginStat != nil {
		return *m.LoginStat
	}
	return IM_BaseDefine.UserStatType_USER_STATUS_ONLINE
}

type IMRemoveSessionNotify struct {
	// cmd id:		0x020f
	UserId           *uint32                    `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SessionType      *IM_BaseDefine.SessionType `protobuf:"varint,2,req,name=session_type,json=sessionType,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId        *uint32                    `protobuf:"varint,3,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *IMRemoveSessionNotify) Reset()                    { *m = IMRemoveSessionNotify{} }
func (m *IMRemoveSessionNotify) String() string            { return proto.CompactTextString(m) }
func (*IMRemoveSessionNotify) ProtoMessage()               {}
func (*IMRemoveSessionNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *IMRemoveSessionNotify) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMRemoveSessionNotify) GetSessionType() IM_BaseDefine.SessionType {
	if m != nil && m.SessionType != nil {
		return *m.SessionType
	}
	return IM_BaseDefine.SessionType_SESSION_TYPE_SINGLE
}

func (m *IMRemoveSessionNotify) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

type IMDepartmentReq struct {
	// cmd id:		0x0210
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime *uint32 `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMDepartmentReq) Reset()                    { *m = IMDepartmentReq{} }
func (m *IMDepartmentReq) String() string            { return proto.CompactTextString(m) }
func (*IMDepartmentReq) ProtoMessage()               {}
func (*IMDepartmentReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *IMDepartmentReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDepartmentReq) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMDepartmentReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMDepartmentRsp struct {
	// cmd id:		0x0211
	UserId           *uint32                     `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	LatestUpdateTime *uint32                     `protobuf:"varint,2,req,name=latest_update_time,json=latestUpdateTime" json:"latest_update_time,omitempty"`
	DeptList         []*IM_BaseDefine.DepartInfo `protobuf:"bytes,3,rep,name=dept_list,json=deptList" json:"dept_list,omitempty"`
	AttachData       []byte                      `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *IMDepartmentRsp) Reset()                    { *m = IMDepartmentRsp{} }
func (m *IMDepartmentRsp) String() string            { return proto.CompactTextString(m) }
func (*IMDepartmentRsp) ProtoMessage()               {}
func (*IMDepartmentRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *IMDepartmentRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMDepartmentRsp) GetLatestUpdateTime() uint32 {
	if m != nil && m.LatestUpdateTime != nil {
		return *m.LatestUpdateTime
	}
	return 0
}

func (m *IMDepartmentRsp) GetDeptList() []*IM_BaseDefine.DepartInfo {
	if m != nil {
		return m.DeptList
	}
	return nil
}

func (m *IMDepartmentRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMAvatarChangedNotify struct {
	// cmd id:		0x02012
	ChangedUserId    *uint32 `protobuf:"varint,1,req,name=changed_user_id,json=changedUserId" json:"changed_user_id,omitempty"`
	AvatarUrl        *string `protobuf:"bytes,2,req,name=avatar_url,json=avatarUrl" json:"avatar_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMAvatarChangedNotify) Reset()                    { *m = IMAvatarChangedNotify{} }
func (m *IMAvatarChangedNotify) String() string            { return proto.CompactTextString(m) }
func (*IMAvatarChangedNotify) ProtoMessage()               {}
func (*IMAvatarChangedNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *IMAvatarChangedNotify) GetChangedUserId() uint32 {
	if m != nil && m.ChangedUserId != nil {
		return *m.ChangedUserId
	}
	return 0
}

func (m *IMAvatarChangedNotify) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

type IMChangeSignInfoReq struct {
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	SignInfo         *string `protobuf:"bytes,2,req,name=sign_info,json=signInfo" json:"sign_info,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMChangeSignInfoReq) Reset()                    { *m = IMChangeSignInfoReq{} }
func (m *IMChangeSignInfoReq) String() string            { return proto.CompactTextString(m) }
func (*IMChangeSignInfoReq) ProtoMessage()               {}
func (*IMChangeSignInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *IMChangeSignInfoReq) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeSignInfoReq) GetSignInfo() string {
	if m != nil && m.SignInfo != nil {
		return *m.SignInfo
	}
	return ""
}

func (m *IMChangeSignInfoReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMChangeSignInfoRsp struct {
	// cmd id:		0x0214
	UserId           *uint32 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ResultCode       *uint32 `protobuf:"varint,2,req,name=result_code,json=resultCode" json:"result_code,omitempty"`
	SignInfo         *string `protobuf:"bytes,3,opt,name=sign_info,json=signInfo" json:"sign_info,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMChangeSignInfoRsp) Reset()                    { *m = IMChangeSignInfoRsp{} }
func (m *IMChangeSignInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*IMChangeSignInfoRsp) ProtoMessage()               {}
func (*IMChangeSignInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *IMChangeSignInfoRsp) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IMChangeSignInfoRsp) GetResultCode() uint32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return 0
}

func (m *IMChangeSignInfoRsp) GetSignInfo() string {
	if m != nil && m.SignInfo != nil {
		return *m.SignInfo
	}
	return ""
}

func (m *IMChangeSignInfoRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 个性签名修改通知（广播）
type IMSignInfoChangedNotify struct {
	// cmd id:		0x0215
	ChangedUserId    *uint32 `protobuf:"varint,1,req,name=changed_user_id,json=changedUserId" json:"changed_user_id,omitempty"`
	SignInfo         *string `protobuf:"bytes,2,req,name=sign_info,json=signInfo" json:"sign_info,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMSignInfoChangedNotify) Reset()                    { *m = IMSignInfoChangedNotify{} }
func (m *IMSignInfoChangedNotify) String() string            { return proto.CompactTextString(m) }
func (*IMSignInfoChangedNotify) ProtoMessage()               {}
func (*IMSignInfoChangedNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *IMSignInfoChangedNotify) GetChangedUserId() uint32 {
	if m != nil && m.ChangedUserId != nil {
		return *m.ChangedUserId
	}
	return 0
}

func (m *IMSignInfoChangedNotify) GetSignInfo() string {
	if m != nil && m.SignInfo != nil {
		return *m.SignInfo
	}
	return ""
}

func init() {
	proto.RegisterType((*IMRecentContactSessionReq)(nil), "IM.Buddy.IMRecentContactSessionReq")
	proto.RegisterType((*IMRecentContactSessionRsp)(nil), "IM.Buddy.IMRecentContactSessionRsp")
	proto.RegisterType((*IMUserStatNotify)(nil), "IM.Buddy.IMUserStatNotify")
	proto.RegisterType((*IMUsersInfoReq)(nil), "IM.Buddy.IMUsersInfoReq")
	proto.RegisterType((*IMUsersInfoRsp)(nil), "IM.Buddy.IMUsersInfoRsp")
	proto.RegisterType((*IMRemoveSessionReq)(nil), "IM.Buddy.IMRemoveSessionReq")
	proto.RegisterType((*IMRemoveSessionRsp)(nil), "IM.Buddy.IMRemoveSessionRsp")
	proto.RegisterType((*IMAllUserReq)(nil), "IM.Buddy.IMAllUserReq")
	proto.RegisterType((*IMAllUserRsp)(nil), "IM.Buddy.IMAllUserRsp")
	proto.RegisterType((*IMUsersStatReq)(nil), "IM.Buddy.IMUsersStatReq")
	proto.RegisterType((*IMUsersStatRsp)(nil), "IM.Buddy.IMUsersStatRsp")
	proto.RegisterType((*IMChangeAvatarReq)(nil), "IM.Buddy.IMChangeAvatarReq")
	proto.RegisterType((*IMChangeAvatarRsp)(nil), "IM.Buddy.IMChangeAvatarRsp")
	proto.RegisterType((*IMPCLoginStatusNotify)(nil), "IM.Buddy.IMPCLoginStatusNotify")
	proto.RegisterType((*IMRemoveSessionNotify)(nil), "IM.Buddy.IMRemoveSessionNotify")
	proto.RegisterType((*IMDepartmentReq)(nil), "IM.Buddy.IMDepartmentReq")
	proto.RegisterType((*IMDepartmentRsp)(nil), "IM.Buddy.IMDepartmentRsp")
	proto.RegisterType((*IMAvatarChangedNotify)(nil), "IM.Buddy.IMAvatarChangedNotify")
	proto.RegisterType((*IMChangeSignInfoReq)(nil), "IM.Buddy.IMChangeSignInfoReq")
	proto.RegisterType((*IMChangeSignInfoRsp)(nil), "IM.Buddy.IMChangeSignInfoRsp")
	proto.RegisterType((*IMSignInfoChangedNotify)(nil), "IM.Buddy.IMSignInfoChangedNotify")
}

func init() { proto.RegisterFile("IM.Buddy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4d, 0x4f, 0xdb, 0x4c,
	0x10, 0x96, 0xc9, 0xab, 0xb7, 0x78, 0x12, 0x3e, 0x6a, 0xa8, 0x12, 0x40, 0x88, 0x34, 0x87, 0x8a,
	0x43, 0x95, 0x03, 0xaa, 0x7a, 0xa8, 0xc4, 0x01, 0xc2, 0x01, 0x4b, 0xb8, 0xaa, 0x1c, 0x72, 0xc5,
	0xda, 0xda, 0x9b, 0xb0, 0x95, 0xe3, 0x75, 0xbd, 0x63, 0xa4, 0x9c, 0x7b, 0xea, 0xa1, 0xfd, 0x21,
	0x15, 0x97, 0xfe, 0x90, 0xfe, 0xa7, 0x6a, 0x77, 0x6d, 0x81, 0x03, 0xb1, 0x4d, 0x69, 0xb9, 0xd9,
	0x33, 0xe3, 0x79, 0x9e, 0xf9, 0x78, 0x26, 0x81, 0x55, 0xdb, 0xe9, 0x1f, 0xa7, 0x41, 0x30, 0xeb,
	0xc7, 0x09, 0x47, 0x6e, 0x2d, 0xe7, 0xef, 0xdb, 0x1b, 0xf2, 0x89, 0x08, 0x7a, 0x42, 0xc7, 0x2c,
	0xa2, 0xda, 0xdd, 0xfb, 0x62, 0xc0, 0x96, 0xed, 0xb8, 0xd4, 0xa7, 0x11, 0x0e, 0x78, 0x84, 0xc4,
	0xc7, 0x21, 0x15, 0x82, 0xf1, 0xc8, 0xa5, 0x9f, 0xad, 0x36, 0x3c, 0x4b, 0x05, 0x4d, 0x3c, 0x16,
	0x74, 0x8c, 0xee, 0xd2, 0xfe, 0x8a, 0xfb, 0xbf, 0x7c, 0xb5, 0x03, 0xeb, 0x35, 0x58, 0x21, 0x41,
	0x2a, 0xd0, 0x4b, 0xe3, 0x80, 0x20, 0xf5, 0x90, 0x4d, 0x69, 0x67, 0x49, 0xc5, 0xac, 0x6b, 0xcf,
	0x48, 0x39, 0xce, 0xd9, 0x94, 0x5a, 0x7b, 0xd0, 0x24, 0x88, 0xc4, 0xbf, 0xf4, 0x02, 0x82, 0xa4,
	0xb3, 0xd9, 0x35, 0xf6, 0x5b, 0x2e, 0x68, 0xd3, 0x09, 0x41, 0xd2, 0xfb, 0xb1, 0x98, 0x85, 0x88,
	0x17, 0xb3, 0x18, 0xc2, 0xa6, 0xaf, 0xa3, 0x3d, 0xa1, 0xc3, 0xbd, 0x90, 0x09, 0xec, 0x2c, 0x75,
	0x1b, 0xfb, 0xcd, 0x83, 0x97, 0xfd, 0x62, 0xc1, 0xc5, 0xc4, 0x76, 0x34, 0xe6, 0xae, 0xe5, 0x17,
	0x6c, 0x67, 0x4c, 0x60, 0x35, 0xd9, 0x53, 0x58, 0xb7, 0x9d, 0x91, 0xa0, 0xc9, 0x10, 0x09, 0xbe,
	0xe7, 0xc8, 0xc6, 0x33, 0xeb, 0x0d, 0x98, 0x8a, 0xa2, 0x40, 0x82, 0x8a, 0x64, 0xf3, 0xa0, 0x3d,
	0x07, 0x9f, 0x7f, 0xe1, 0x2e, 0xa7, 0xd9, 0x53, 0x2f, 0x94, 0xd3, 0x92, 0x76, 0xa1, 0xd8, 0x94,
	0x35, 0xbc, 0x0b, 0xad, 0xcc, 0x71, 0x53, 0xe2, 0x8a, 0x0b, 0xda, 0x5b, 0x8f, 0xf7, 0x57, 0xa3,
	0x08, 0x57, 0xd6, 0xd9, 0x43, 0x58, 0xd5, 0x8e, 0x68, 0xcc, 0x6f, 0xf7, 0xf4, 0xbe, 0xa2, 0x54,
	0x32, 0xc5, 0x4e, 0x3e, 0xd5, 0xe3, 0x72, 0x6d, 0x80, 0x25, 0x07, 0x3e, 0xe5, 0x57, 0xb4, 0xce,
	0xbe, 0x1d, 0x42, 0x2b, 0x9f, 0x30, 0xce, 0x62, 0xbd, 0x69, 0xab, 0x07, 0xdb, 0x73, 0x6c, 0xb2,
	0x4c, 0xe7, 0xb3, 0x98, 0xba, 0x4d, 0x71, 0xf3, 0x62, 0xed, 0x02, 0xe4, 0x9f, 0xb3, 0xa0, 0xd3,
	0x50, 0xa9, 0xcd, 0xcc, 0x62, 0x07, 0xd5, 0x74, 0x7f, 0xdd, 0x43, 0xb7, 0xac, 0x7d, 0x7b, 0xd0,
	0x4c, 0xa8, 0x48, 0x43, 0xf4, 0x7c, 0x1e, 0xe4, 0xba, 0x00, 0x6d, 0x1a, 0xf0, 0x80, 0xde, 0xa9,
	0xa7, 0xf1, 0x98, 0x7a, 0xfe, 0x7b, 0x70, 0x3d, 0x57, 0xd0, 0xb2, 0x9d, 0xa3, 0x30, 0x94, 0xe3,
	0x7b, 0x4a, 0x9d, 0x5f, 0x1b, 0xb7, 0x81, 0xcb, 0x3a, 0xf8, 0x30, 0xe0, 0x5c, 0x7e, 0x6a, 0x53,
	0x1b, 0xe5, 0x9b, 0xaa, 0xe4, 0x57, 0x6f, 0x4b, 0x6f, 0xf4, 0xa9, 0x84, 0xfb, 0x74, 0xfa, 0x54,
	0x70, 0x75, 0xf4, 0x29, 0xef, 0x4d, 0x95, 0x3e, 0x55, 0xb2, 0x56, 0x7e, 0x74, 0xea, 0x56, 0xfe,
	0xdc, 0x76, 0x06, 0x97, 0x24, 0x9a, 0xd0, 0xa3, 0x2b, 0x82, 0xa4, 0x7c, 0x4b, 0x76, 0x01, 0x88,
	0x8a, 0xf2, 0xd2, 0x24, 0x54, 0x43, 0x32, 0x5d, 0x53, 0x5b, 0x46, 0x49, 0x58, 0x8d, 0x16, 0xdd,
	0x41, 0x7b, 0x94, 0xb8, 0x6a, 0x54, 0xf7, 0xc2, 0x76, 0x3e, 0x0c, 0xce, 0xf8, 0x84, 0x45, 0xb2,
	0x27, 0xa9, 0xc8, 0xce, 0xf8, 0x42, 0xcc, 0x77, 0x00, 0xa1, 0x8c, 0xd6, 0x07, 0x5e, 0x5f, 0x9f,
	0x9d, 0x05, 0xbd, 0x56, 0x72, 0x35, 0xc3, 0x3c, 0x79, 0xef, 0xbb, 0x21, 0xe1, 0x0a, 0xc7, 0xa3,
	0x0a, 0xee, 0x9f, 0x9e, 0xbb, 0xde, 0x0c, 0xd6, 0x6c, 0xe7, 0x84, 0xc6, 0x24, 0xc1, 0x29, 0x8d,
	0xf0, 0x29, 0x0f, 0xc0, 0x4f, 0x63, 0x0e, 0xfb, 0xef, 0xdd, 0x80, 0xb7, 0x60, 0x06, 0x34, 0xc6,
	0xdb, 0x37, 0x60, 0x6b, 0xae, 0x61, 0x1a, 0x57, 0x5f, 0x01, 0x19, 0x5b, 0x4f, 0x0b, 0x17, 0x72,
	0x7c, 0x7a, 0x2f, 0xf5, 0x8e, 0x06, 0xd9, 0xf8, 0x5e, 0xc1, 0x9a, 0xaf, 0x0d, 0x5e, 0xb1, 0x80,
	0x95, 0xcc, 0x3c, 0xaa, 0x23, 0x8f, 0x5e, 0x08, 0x1b, 0xf9, 0xf6, 0x0f, 0xd9, 0x24, 0xaa, 0xfc,
	0x2b, 0xb0, 0x03, 0xa6, 0x60, 0x93, 0x48, 0xfd, 0x36, 0x67, 0xd9, 0x96, 0x45, 0xf6, 0x61, 0x75,
	0x35, 0xdf, 0x8c, 0x7b, 0xe0, 0x1e, 0x25, 0xb7, 0x02, 0x9f, 0x46, 0xd7, 0x78, 0x18, 0x9f, 0x0b,
	0x68, 0xdb, 0x4e, 0x4e, 0xe4, 0xcf, 0xfa, 0x5b, 0xd6, 0x90, 0xe3, 0x1d, 0x68, 0xfb, 0x7c, 0xda,
	0x9f, 0xf2, 0x49, 0xfa, 0x89, 0xd1, 0x3e, 0xa2, 0xfe, 0xe3, 0xfb, 0x31, 0x1d, 0x9f, 0x36, 0x7e,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x06, 0xbe, 0x2d, 0x2d, 0x0b, 0x00, 0x00,
}
